
name: reviewdog
on: push
jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pylint --generate-rcfile > ~/.pylintrc

      - name: Setup reviewdog
        run: |
          mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $HOME/bin
          echo ::add-path::$HOME/bin

      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPEN_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pylint --rcfile=~/.pylintrc src/make_emb.py --pdf_url "https://arxiv.org/pdf/2003.08934" --OPEN_API_KEY ${{ env.OPEN_API_KEY }} | reviewdog -efm="%f:%l:%c: %m" -reporter=github-pr-review
          pylint --rcfile=~/.pylintrc src/pdf_qa.py --query "On which datasets does GPT-3 struggle?" | reviewdog -efm="%f:%l:%c: %m" -reporter=github-pr-review
