
name: reviewdog
on: 
  pull_request:
    branches:
      - develop
jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.10

      - name: Setup pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pylint --generate-rcfile > ~/.pylintrc

      - name: Setup reviewdog
        run: |
          mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $HOME/bin
          echo ::add-path::$HOME/bin

      - name: Run reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPEN_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pylint --rcfile=~/.pylintrc src/make_emb.py --pdf_url "https://arxiv.org/pdf/2003.08934" --OPEN_API_KEY OPEN_API_KEY | reviewdog -efm="%f:%l:%c: %m" -reporter=github-pr-review
          pylint --rcfile=~/.pylintrc src/pdf_qa.py --query "On which datasets does GPT-3 struggle?" | reviewdog -efm="%f:%l:%c: %m" -reporter=github-pr-review
